-- =============================================================
-- 005 — Loja integrada
-- Admin cadastra produtos; o cliente (conta própria) faz o pedido;
-- o pedido cai na fila do admin, que entra em contato e fecha a venda.
-- Não há pagamento online: o fechamento é manual.
--
-- Clientes ficam em `customers`, e não em `users`, de propósito:
-- `users` é a árvore de afiliados e carrega triggers de recrutamento (3x),
-- ciclo mensal e graduação. Um cliente nessa tabela geraria pontos de
-- recrutamento e entraria no fechamento mensal.
-- =============================================================

do $$ begin
  create type public.order_status as enum ('novo', 'em_contato', 'fechado', 'cancelado');
exception when duplicate_object then null; end $$;

-- -------------------------------------------------------------
-- Clientes finais
-- -------------------------------------------------------------
create table if not exists public.customers (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text not null,
  email       text,
  phone       text,
  address     text,
  -- afiliado que trouxe o cliente (link da loja)
  referred_by uuid references public.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists customers_referred_by_idx on public.customers (referred_by);

drop trigger if exists customers_touch_updated_at on public.customers;
create trigger customers_touch_updated_at
  before update on public.customers
  for each row execute function public.fn_touch_updated_at();

-- -------------------------------------------------------------
-- Catálogo
-- price_cents evita erro de arredondamento de ponto flutuante
-- points_value é quanto a venda deste produto injeta na rede
-- -------------------------------------------------------------
create table if not exists public.products (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  description  text,
  sku          text unique,
  price_cents  int  not null check (price_cents >= 0),
  points_value int  not null default 0 check (points_value >= 0),
  image_url    text,
  is_active    boolean not null default true,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists products_active_idx on public.products (is_active, sort_order);

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
  before update on public.products
  for each row execute function public.fn_touch_updated_at();

-- -------------------------------------------------------------
-- Pedidos
-- Totais e pontos são snapshots calculados no servidor no momento
-- do pedido — o cliente nunca envia preço nem pontuação.
-- -------------------------------------------------------------
create table if not exists public.orders (
  id            uuid primary key default gen_random_uuid(),
  order_number  bigint generated by default as identity,
  customer_id   uuid not null references public.customers (id) on delete cascade,
  -- snapshot do contato: o admin precisa ligar mesmo se o cliente editar o perfil
  contact_name  text not null,
  contact_phone text not null,
  contact_email text,
  address       text,
  customer_notes text,
  referred_by   uuid references public.users (id) on delete set null,
  status        public.order_status not null default 'novo',
  total_cents   int not null default 0 check (total_cents >= 0),
  total_points  int not null default 0 check (total_points >= 0),
  admin_notes   text,
  contacted_at  timestamptz,
  closed_at     timestamptz,
  cancelled_at  timestamptz,
  reviewed_by   uuid references public.users (id) on delete set null,
  created_at    timestamptz not null default now()
);

create unique index if not exists orders_order_number_idx on public.orders (order_number);
create index if not exists orders_status_idx      on public.orders (status, created_at desc);
create index if not exists orders_customer_idx    on public.orders (customer_id, created_at desc);
create index if not exists orders_referred_by_idx on public.orders (referred_by);

create table if not exists public.order_items (
  id               uuid primary key default gen_random_uuid(),
  order_id         uuid not null references public.orders (id) on delete cascade,
  product_id       uuid references public.products (id) on delete set null,
  -- snapshots: o histórico do pedido não muda se o produto for editado
  product_name     text not null,
  quantity         int  not null check (quantity between 1 and 999),
  unit_price_cents int  not null check (unit_price_cents >= 0),
  unit_points      int  not null check (unit_points >= 0),
  created_at       timestamptz not null default now()
);

create index if not exists order_items_order_idx on public.order_items (order_id);

-- -------------------------------------------------------------
-- Liga vendas ao pedido/produto de origem
-- -------------------------------------------------------------
alter table public.sales
  add column if not exists order_id   uuid references public.orders (id) on delete set null,
  add column if not exists product_id uuid references public.products (id) on delete set null;

create index if not exists sales_order_id_idx on public.sales (order_id);

-- =============================================================
-- Estorno de pontos de uma venda (extraído para ser reutilizado
-- pelo cancelamento de venda e pelo cancelamento de pedido fechado)
-- =============================================================
create or replace function public.fn_reverse_sale_points(p_sale_id uuid)
returns int
language sql
security definer
set search_path = public
as $$
  with inserted as (
    insert into public.points_ledger
      (user_id, source_user_id, origin, base_points, multiplier, level,
       sale_id, is_reversal, reverses_id, description)
    select l.user_id, l.source_user_id, l.origin, -l.base_points, l.multiplier, l.level,
           l.sale_id, true, l.id, 'Estorno de venda cancelada'
    from public.points_ledger l
    where l.sale_id = p_sale_id
      and not l.is_reversal
      and not exists (select 1 from public.points_ledger r where r.reverses_id = l.id)
    returning 1
  )
  select count(*)::int from inserted;
$$;

-- review_sale_cancellation passa a usar o helper
create or replace function public.review_sale_cancellation(
  p_sale_id uuid,
  p_approve boolean
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem revisar cancelamentos';
  end if;

  select * into v_sale from public.sales where id = p_sale_id for update;

  if v_sale.id is null then
    raise exception 'Venda não encontrada';
  end if;

  if v_sale.status <> 'pendente_cancelamento' then
    raise exception 'Esta venda não está aguardando revisão de cancelamento';
  end if;

  if p_approve then
    perform public.fn_reverse_sale_points(p_sale_id);

    update public.sales
       set status = 'cancelada', cancelled_at = now(), reviewed_by = auth.uid()
     where id = p_sale_id
    returning * into v_sale;
  else
    update public.sales
       set status = 'ativa', cancel_reason = null,
           cancel_requested_at = null, reviewed_by = auth.uid()
     where id = p_sale_id
    returning * into v_sale;
  end if;

  return v_sale;
end;
$$;

-- =============================================================
-- CLIENTE: registrar pedido
-- p_items: [{"product_id": "uuid", "quantity": 2}, ...]
-- Preço e pontos vêm sempre do catálogo, nunca do cliente.
-- =============================================================
create or replace function public.place_order(
  p_items    jsonb,
  p_phone    text,
  p_address  text default null,
  p_notes    text default null,
  p_ref      text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer  public.customers;
  v_order_id  uuid;
  v_number    bigint;
  v_ref       uuid;
  v_count     int;
  v_total     int;
  v_points    int;
begin
  select * into v_customer from public.customers where id = auth.uid();
  if v_customer.id is null then
    raise exception 'Crie uma conta de cliente para finalizar o pedido';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'O carrinho está vazio';
  end if;

  if jsonb_array_length(p_items) > 50 then
    raise exception 'Máximo de 50 itens diferentes por pedido';
  end if;

  if coalesce(btrim(p_phone), '') = '' then
    raise exception 'Informe um telefone para o contato do pedido';
  end if;

  -- afiliado do link usado agora; se não vier, o que trouxe o cliente
  if p_ref is not null then
    select id into v_ref from public.users where username = lower(btrim(p_ref));
  end if;
  v_ref := coalesce(v_ref, v_customer.referred_by);

  insert into public.orders
    (customer_id, contact_name, contact_phone, contact_email, address, customer_notes, referred_by)
  values
    (v_customer.id, v_customer.full_name, btrim(p_phone), v_customer.email,
     coalesce(nullif(btrim(coalesce(p_address, '')), ''), v_customer.address),
     nullif(btrim(coalesce(p_notes, '')), ''), v_ref)
  returning id, order_number into v_order_id, v_number;

  -- monta os itens a partir do catálogo ativo
  with req as (
    select (item ->> 'product_id')::uuid as product_id,
           greatest(1, least(999, coalesce((item ->> 'quantity')::int, 1))) as quantity
    from jsonb_array_elements(p_items) item
  ),
  ins as (
    insert into public.order_items
      (order_id, product_id, product_name, quantity, unit_price_cents, unit_points)
    select v_order_id, p.id, p.name, r.quantity, p.price_cents, p.points_value
    from req r
    join public.products p on p.id = r.product_id and p.is_active
    returning quantity, unit_price_cents, unit_points
  )
  select count(*)::int,
         coalesce(sum(quantity * unit_price_cents), 0)::int,
         coalesce(sum(quantity * unit_points), 0)::int
    into v_count, v_total, v_points
  from ins;

  if v_count = 0 then
    raise exception 'Nenhum produto válido no carrinho';
  end if;

  update public.orders
     set total_cents = v_total, total_points = v_points
   where id = v_order_id;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_number,
    'items', v_count,
    'total_cents', v_total,
    'total_points', v_points
  );
end;
$$;

-- =============================================================
-- ADMIN: tocar o pedido
-- =============================================================
create or replace function public.mark_order_contacted(
  p_order_id uuid,
  p_notes    text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem atualizar pedidos';
  end if;

  update public.orders
     set status = 'em_contato',
         contacted_at = coalesce(contacted_at, now()),
         admin_notes = coalesce(p_notes, admin_notes),
         reviewed_by = auth.uid()
   where id = p_order_id
     and status in ('novo', 'em_contato')
  returning * into v_order;

  if v_order.id is null then
    raise exception 'Pedido não encontrado ou já finalizado';
  end if;

  return v_order;
end;
$$;

-- Fechar a venda: gera UMA venda por item, para que a contagem de
-- produtos da ativação mensal e os pontos fiquem ambos corretos.
-- Cada insert em sales dispara o motor de pontos já existente
-- (peso 1x + compressão dinâmica até o 5º nível).
create or replace function public.close_order(
  p_order_id uuid,
  p_notes    text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_sales int := 0;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem fechar pedidos';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;

  if v_order.id is null then
    raise exception 'Pedido não encontrado';
  end if;

  if v_order.status = 'fechado' then
    raise exception 'Pedido já está fechado';
  end if;

  if v_order.status = 'cancelado' then
    raise exception 'Pedido cancelado não pode ser fechado';
  end if;

  if v_order.referred_by is not null then
    with created as (
      insert into public.sales
        (user_id, product_name, quantity, base_points, customer_name,
         notes, order_id, product_id)
      select v_order.referred_by, i.product_name, i.quantity, i.unit_points,
             v_order.contact_name,
             format('Pedido #%s da loja', v_order.order_number),
             v_order.id, i.product_id
      from public.order_items i
      where i.order_id = p_order_id
      returning 1
    )
    select count(*)::int into v_sales from created;
  end if;

  update public.orders
     set status = 'fechado',
         closed_at = now(),
         admin_notes = coalesce(p_notes, admin_notes),
         reviewed_by = auth.uid()
   where id = p_order_id;

  return jsonb_build_object(
    'order_id', p_order_id,
    'sales_created', v_sales,
    'points_distributed', v_order.referred_by is not null,
    'total_points', v_order.total_points
  );
end;
$$;

-- Cancelar. Se o pedido já estava fechado, estorna os pontos que ele
-- injetou na rede e marca as vendas geradas como canceladas.
create or replace function public.cancel_order(
  p_order_id uuid,
  p_notes    text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order    public.orders;
  v_sale     record;
  v_reversed int := 0;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem cancelar pedidos';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;

  if v_order.id is null then
    raise exception 'Pedido não encontrado';
  end if;

  if v_order.status = 'cancelado' then
    raise exception 'Pedido já está cancelado';
  end if;

  if v_order.status = 'fechado' then
    for v_sale in
      select id from public.sales
      where order_id = p_order_id and status <> 'cancelada'
    loop
      v_reversed := v_reversed + public.fn_reverse_sale_points(v_sale.id);
      update public.sales
         set status = 'cancelada', cancelled_at = now(), reviewed_by = auth.uid()
       where id = v_sale.id;
    end loop;
  end if;

  update public.orders
     set status = 'cancelado',
         cancelled_at = now(),
         admin_notes = coalesce(p_notes, admin_notes),
         reviewed_by = auth.uid()
   where id = p_order_id;

  return jsonb_build_object('order_id', p_order_id, 'ledger_rows_reversed', v_reversed);
end;
$$;

-- =============================================================
-- Signup: decide entre afiliado e cliente pelo metadata
-- =============================================================
create or replace function public.fn_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sponsor  uuid;
  v_username text;
  v_role     text := lower(coalesce(new.raw_user_meta_data ->> 'role', 'affiliate'));
begin
  select id into v_sponsor
  from public.users
  where username = lower(new.raw_user_meta_data ->> 'sponsor_username');

  -- cliente da loja: não entra na árvore de afiliados
  if v_role = 'customer' then
    insert into public.customers (id, full_name, email, phone, referred_by)
    values (
      new.id,
      coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
      new.email,
      new.raw_user_meta_data ->> 'phone',
      v_sponsor
    );
    return new;
  end if;

  v_username := lower(coalesce(
    new.raw_user_meta_data ->> 'username',
    split_part(new.email, '@', 1)
  ));
  v_username := regexp_replace(v_username, '[^a-z0-9._-]', '', 'g');

  if length(v_username) < 3 then
    v_username := 'user' || substr(replace(new.id::text, '-', ''), 1, 8);
  end if;

  if exists (select 1 from public.users where username = v_username) then
    v_username := v_username || substr(replace(new.id::text, '-', ''), 1, 6);
  end if;

  insert into public.users (id, sponsor_id, username, full_name, email)
  values (
    new.id,
    v_sponsor,
    v_username,
    coalesce(new.raw_user_meta_data ->> 'full_name', v_username),
    new.email
  );

  return new;
end;
$$;

-- =============================================================
-- Views do painel admin
-- =============================================================
create or replace view public.v_admin_orders
with (security_invoker = true) as
select
  o.id,
  o.order_number,
  o.status,
  o.contact_name,
  o.contact_phone,
  o.contact_email,
  o.address,
  o.customer_notes,
  o.admin_notes,
  o.total_cents,
  o.total_points,
  o.created_at,
  o.contacted_at,
  o.closed_at,
  o.cancelled_at,
  o.customer_id,
  o.referred_by,
  u.username as referred_by_username,
  u.full_name as referred_by_name,
  (select count(*) from public.order_items i where i.order_id = o.id) as item_count,
  coalesce(
    (select jsonb_agg(jsonb_build_object(
       'product_name', i.product_name,
       'quantity', i.quantity,
       'unit_price_cents', i.unit_price_cents,
       'unit_points', i.unit_points
     ) order by i.product_name)
     from public.order_items i where i.order_id = o.id),
    '[]'::jsonb
  ) as items
from public.orders o
left join public.users u on u.id = o.referred_by
order by
  case o.status when 'novo' then 0 when 'em_contato' then 1 when 'fechado' then 2 else 3 end,
  o.created_at desc;

-- Estatísticas do admin, agora incluindo a loja
create or replace function public.get_admin_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case when not public.is_admin() then '{}'::jsonb else jsonb_build_object(
    'total_users',           (select count(*) from public.users where not is_admin),
    'active_users',          (select count(*) from public.users where not is_admin and not is_inactive),
    'inactive_users',        (select count(*) from public.users where not is_admin and is_inactive),
    'at_risk_users',         (select count(*) from public.users where not is_admin and not is_inactive and inactive_streak >= 2),
    'pending_cancellations', (select count(*) from public.sales where status = 'pendente_cancelamento'),
    'pending_prizes',        (select count(*) from public.prize_requests where status = 'solicitado'),
    'sales_this_month',      (select coalesce(sum(quantity), 0) from public.sales
                               where status = 'ativa'
                                 and date_trunc('month', sold_at) = date_trunc('month', now())),
    'points_this_month',     (select coalesce(sum(points), 0) from public.points_ledger
                               where level = 0
                                 and date_trunc('month', created_at) = date_trunc('month', now())),
    'open_orders',           (select count(*) from public.orders where status in ('novo', 'em_contato')),
    'new_orders',            (select count(*) from public.orders where status = 'novo'),
    'orders_revenue_month',  (select coalesce(sum(total_cents), 0) from public.orders
                               where status = 'fechado'
                                 and date_trunc('month', closed_at) = date_trunc('month', now())),
    'active_products',       (select count(*) from public.products where is_active),
    'total_customers',       (select count(*) from public.customers)
  ) end;
$$;

grant execute on function public.get_admin_stats() to authenticated;

-- =============================================================
-- RLS
-- =============================================================
alter table public.customers   enable row level security;
alter table public.products    enable row level security;
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;

-- customers: o cliente vê/edita só a si mesmo; admin gerencia.
-- O afiliado NÃO enxerga a base de clientes (dado pessoal de terceiro).
drop policy if exists customers_select_self on public.customers;
create policy customers_select_self on public.customers
  for select to authenticated using (id = auth.uid());

drop policy if exists customers_update_self on public.customers;
create policy customers_update_self on public.customers
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists customers_all_admin on public.customers;
create policy customers_all_admin on public.customers
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- A atribuição do cliente ao afiliado é comissionável: sem esta trava o
-- cliente poderia se desvincular ou apontar para outro afiliado e roubar
-- os pontos do pedido.
create or replace function public.fn_customers_guard_referral()
returns trigger
language plpgsql
as $$
begin
  if current_user not in ('authenticated', 'anon') or public.is_admin() then
    return new;
  end if;

  if new.id is distinct from old.id
     or new.referred_by is distinct from old.referred_by then
    raise exception 'Alteração não permitida: o vínculo com o afiliado é gerido pelo sistema';
  end if;

  return new;
end;
$$;

drop trigger if exists customers_guard_referral on public.customers;
create trigger customers_guard_referral
  before update on public.customers
  for each row execute function public.fn_customers_guard_referral();

-- products: catálogo ativo é público (a vitrine abre sem login)
drop policy if exists products_select_active on public.products;
create policy products_select_active on public.products
  for select to authenticated, anon
  using (is_active or public.is_admin());

drop policy if exists products_write_admin on public.products;
create policy products_write_admin on public.products
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- orders: o cliente vê os próprios; o afiliado vê os que indicou;
-- escrita é sempre via RPC (place_order / close_order / cancel_order).
drop policy if exists orders_select_customer on public.orders;
create policy orders_select_customer on public.orders
  for select to authenticated using (customer_id = auth.uid());

drop policy if exists orders_select_referrer on public.orders;
create policy orders_select_referrer on public.orders
  for select to authenticated using (referred_by = auth.uid());

drop policy if exists orders_select_admin on public.orders;
create policy orders_select_admin on public.orders
  for select to authenticated using (public.is_admin());

drop policy if exists orders_all_admin on public.orders;
create policy orders_all_admin on public.orders
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_items_select on public.order_items;
create policy order_items_select on public.order_items
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and (o.customer_id = auth.uid() or o.referred_by = auth.uid() or public.is_admin())
  ));

drop policy if exists order_items_all_admin on public.order_items;
create policy order_items_all_admin on public.order_items
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- =============================================================
-- Grants
-- =============================================================
grant select on public.products to authenticated, anon;
grant insert, update, delete on public.products to authenticated;
grant select, update on public.customers to authenticated;
grant insert, update, delete on public.customers to authenticated;
grant select on public.orders, public.order_items to authenticated;
grant insert, update, delete on public.orders, public.order_items to authenticated;
grant select on public.v_admin_orders to authenticated;

grant execute on function public.place_order(jsonb, text, text, text, text) to authenticated;
grant execute on function public.mark_order_contacted(uuid, text)           to authenticated;
grant execute on function public.close_order(uuid, text)                    to authenticated;
grant execute on function public.cancel_order(uuid, text)                   to authenticated;

revoke execute on function public.fn_reverse_sale_points(uuid) from authenticated, anon;
